name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@latest
  quality-check:
    name: "Quality Check"
    uses: NHSDigital/uec-dos-management/.github/workflows/quality-checks.yaml@latest
    needs:
      [
        metadata,
      ]
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["github-runner", "terraform_management", "application"]'
    secrets: inherit
  unit-tests:
    name: Unit Test
    needs:
      [
        metadata,
        quality-check,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/unit-test.yaml@latest
    with:
      env: dev
    secrets: inherit
  slack-notifications:
    name: Send notification to slack
    needs: [
      metadata,
      quality-check,
      unit-tests
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@latest
    with:
      env: dev
    secrets: inherit
