name: Pipeline Deployment Application Test Environment

on:
  workflow_call:
    inputs:
      workspace:
        description: "The workspace to deploy the service into"
        required: true
        type: string
      tag:
        description: "Defines the tag to be used for deployment"
        required: true
        type: string
      commit_hash:
        description: "The commit hash to identify the version of artefacts"
        required: true
        type: string
      artefact_bucket_name:
        description: "The name of domain repository for artefacts"
        required: true
        type: string

jobs:
  deploy-application-infrastructure:
    name: Deploy application infrastructure
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@latest
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
      domain: "uec-dos-service-management"
      stacks: "['application', 'domain-test']"
      tag: ${{ inputs.tag }}
      action: apply
    secrets: inherit
  deploy-application:
    name: Deploy lambda application code
    needs:
      [
        deploy-application-infrastructure,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/deploy-lambda-code.yaml@latest
    with:
      directory: 'application'
      environment: test
      workspace: ${{ inputs.workspace }}
      services:
        "[
          'healthcare-services-data-manager',
          'locations-data-manager',
          'organisation-affiliations-data-manager',
          'organisations-data-manager',
          'questionnaire-responses-data-manager',
          'questionnaires-data-manager'
        ]"
      commit_hash: ${{ inputs.commit_hash }}
      artefact_bucket_name: ${{ inputs.artefact_bucket_name }}
    secrets: inherit

  domain-tests:
    name: Run domain tests
    needs:
      [
        deploy-application-infrastructure,
        deploy-application,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/domain-test.yaml@latest
    with:
      environment: test
      workspace: ${{ inputs.workspace }}
    secrets: inherit
